### ISSUE TITLE
WebPage Html Css

### ISSUE THREAD

**Issue by fakaradut** [fakaradut/messages-application-html-css#2]
![psdToHtmlCss](https://user-images.githubusercontent.com/58641475/94718108-e7270980-0359-11eb-8d56-6e85b4cbdcb6.png)

**Comment by Shubhainder** [comment]
What help do you need?

**Comment by fakaradut** [comment]
Thank you for asking but i opened this issue because i want to add image on readme file. But after, i learned this was not necessary.
